### ISSUE TITLE
Needs to relog when xauth expires

### ISSUE THREAD

**Issue by Simen-Jens** [Simen-Jens/Tindava#16]
When the xauth token provided by Tinder expires, the bot needs to get a way to authenticate again. Pinging user is ok, generating from a fully pledged Facebook account would potentially be better.

**Comment by WhiskeyHammer** [comment]
Interesting. Did you happen to notice how long the xauth tokens were good for?

**Comment by Simen-Jens** [comment]
The tokens from Tinders side seems to be valid for quite a while, as long as you don't generate a new one. I'd say as long as 15-20 hours.
